<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SJ '. $this->translate('Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
       <!-- Styles -->
       <?php 
       /*echo $this->headstyle('a{}', $placement = 'PREPEND', $attributes= array());*/       
       ?>
    </head>
    <body>
    	
        <nav class="navbar navbar-default navbar-fixed-top"  role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#" style="padding: 0px"><img width="60px" height="60px" src="<?php echo $this->basePath('img/logo.svg') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" style="margin-top:10px;">
                    	<li  class="active"><a href="login" style="color:green;">Login</a></li>
                       <!-- 
                       <li><a href="#" style="color:green;"><?php echo "Link" ?></a></li>
                       <li><a href="#" style="color:green;"><?php echo "Link" ?></a></li>                       
                       <li class="dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:green;">Dropdown <b class="caret"></b></a>
                       		<ul class="dropdown-menu">
                       			<li><a href="#" style="color:green;">Action</a></li>
                       		</ul>
                       </li>
                        -->
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container" style="margin-top:50px;">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Sowndarrajan Jayapal. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
